name: Publish Release

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - .github/workflows/*
      - README.md
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          cache: true
          cache-dependency-path: './packages.lock.json'
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}} 
      - name: Build
        run: |
          dotnet publish 'Flow.Launcher.Plugin.QuickLook.csproj' -r win-x64  -c Release -o "QuickLook-${{steps.version.outputs.prop}}"
          7z a -tzip "QuickLook-${{steps.version.outputs.prop}}.zip" "./QuickLook-${{steps.version.outputs.prop}}/*"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "QuickLook*"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
